service: sixteen-gpt-email
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-west-2'}
  stage: prod
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'ses:*'
          Resource: '*'
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::16gemail*'
  deploymentBucket:
    name: sls-deployment-${aws:accountId}-${opt:region, 'us-west-2'}

functions:
  Forwarder:
    handler: index.handler

plugins:
  - serverless-deployment-bucket

resources:
  Resources:
    Route53HostedZone:
      Type: AWS::Route53::HostedZone
      Properties:
        HostedZoneConfig:
          Comment: "Domain registered with AWS"
        Name: "16geneticpersonalitytypes.com"

    # Forward email to us-west for SES processing
    Route53RecordSet:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId:
          Ref: Route53HostedZone
        Name: 16geneticpersonalitytypes.com
        Comment: Incoming email record for sub-domain
        Type: MX
        TTL: 900
        ResourceRecords:
          - "10 inbound-smtp.us-west-2.amazonaws.com"
    SESReceiptRuleSet:
      Type: AWS::SES::ReceiptRuleSet
      Properties:
        RuleSetName: '16G'
    EmailRule:
      Type: AWS::SES::ReceiptRule
      Properties:
        RuleSetName: !Ref SESReceiptRuleSet
        Rule:
          Name: '16GIncoming'
          Enabled: True
          Recipients:
            - 16geneticpersonalitytypes.com
          Actions:
            -
              S3Action:
                BucketName: 16gemail
      DependsOn: S3BucketPolicy
    S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 16gemail
        PolicyDocument:
          Statement:
            - Sid: "AllowSESPutObject"
              Effect: "Allow"
              Principal:
                Service: "ses.amazonaws.com"
              Action:
                - "s3:PutObject"
              Resource: 16gemail/*
