service: sixteen-g-email
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-west-2'}
  stage: prod
  iam:
    role:
      Fn::GetAtt:
        - IAMRole
        - Arn
  deploymentBucket:
    name: sls-deployment-${aws:accountId}-${opt:region, 'us-west-2'}

functions:
  Forwarder:
    handler: index.handler

plugins:
  - serverless-deployment-bucket

resources:
  Resources:
    Route53HostedZone:
      Type: AWS::Route53::HostedZone
      Properties:
        HostedZoneConfig:
          Comment: "Domain registered with AWS"
        Name: "16geneticpersonalitytypes.com"

    # Forward email to us-west for SES processing
    Route53RecordSet:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId:
          Ref: Route53HostedZone
        Name: 16geneticpersonalitytypes.com
        Comment: Incoming email record for sub-domain
        Type: MX
        TTL: 900
        ResourceRecords:
          - "10 inbound-smtp.us-west-2.amazonaws.com"
    SESReceiptRuleSet:
      Type: AWS::SES::ReceiptRuleSet
      Properties:
        RuleSetName: 'INBOUND'
    EmailRule16GPT:
      Type: AWS::SES::ReceiptRule
      Properties:
        RuleSetName: !Ref SESReceiptRuleSet
        Rule:
          Name: '16GPT'
          Enabled: True
          Recipients:
            - 16geneticpersonalitytypes.com
          Actions:
            -
              S3Action:
                BucketName: 16gemail
#    EmailRule16Geniuses:
#      Type: AWS::SES::ReceiptRule
#      Properties:
#        RuleSetName: !Ref SESReceiptRuleSet
#        Rule:
#          Name: '16Geniuses'
#          Enabled: True
#          Recipients:
#            - 16geniuses.com
#          Actions:
#            -
#              S3Action:
#                BucketName: 16gemail
#                Prefix: /mail
#      DependsOn: S3BucketPolicy
    S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 16gemail
        PolicyDocument:
          Statement:
            - Sid: "AllowSESPutObject"
              Effect: "Allow"
              Principal:
                Service: "ses.amazonaws.com"
              Action:
                - "s3:PutObject"
              Resource: arn:aws:s3:::16gemail/*
    IAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: 16G-Serverless-Deployment
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - 'cloudformation.amazonaws.com'
                  - 'lambda.amazonaws.com'
              Action:
                - 'sts:AssumeRole'
        Policies:
          - PolicyName: ServerlessDeploymentPolicies
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow   # Allow S3 actions to buckets with service prefix.
                  Resource:
                    - 'arn:aws:s3:::16gemail*'
                  Action:
                    - 's3:*'
          - PolicyName: LambdaRole
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow   # Allow all IAM actions to roles prefixed with service
                  Resource:
                    - !Sub 'arn:aws:iam::${AWS::AccountId}:role/16G-Serverless-Deployment-Role'
                  Action:
                    - 'iam:PassRole'
