service: sixteen-gpt-email
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-west-2'}
  stage: prod
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'ses:*'
          Resource: '*'
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::16gpt.com/*'
  deploymentBucket:
    name: sls-deployment-${aws:accountId}-${opt:region, 'us-west-2'}

functions:
  forwarder:
    handler: index.handler

plugins:
  - serverless-deployment-bucket

