service: ses-email-forwarder
frameworkVersion: '3'

params:
  default:
    bucket: 16-g-mail-test
    region: us-west-2

provider:
  name: aws
  runtime: nodejs18.x
  region: ${param:region}
  stage: prod
  iam:
    role:
      Fn::GetAtt:
        - IAMRole
        - Arn
  deploymentBucket:
    name: sls-deployment-${aws:accountId}-${param:region}

functions:
  Forwarder:
    handler: index.handler
    url: true
    events:
      - s3:
          bucket: ${param:bucket}
          event: s3:ObjectCreated:*
          existing: true   # We are using an existing bucket

plugins:
  - serverless-deployment-bucket
  - serverless-domain-manager
  - serverless-certificate-creator

custom:
  hostedZone:
    name: 16geneticpersonalitytypes.com.
  domain:
    name: 16geneticpersonalitytypes.com
  customDomain:
    domainName: 16geneticpersonalitytypes.com
    certificateName: 16geneticpersonalitytypes.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  customCertificate:
    hostedZoneNames:
      - 16geneticpersonalitytypes.com.
    certificateName: ${self:custom.domain.name}
    region: ${param:region}
    enabled: true
    rewriteRecords: false
    subjectAlternativeNames:
      - dev.${self:custom.domain.name}

resources:
  Resources:
    Route53RecordSet16GPT:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: 16geneticpersonalitytypes.com
        Name: 16geneticpersonalitytypes.com
        Comment: Incoming email record for sub-domain
        Type: MX
        TTL: 900
        ResourceRecords:
          - 10 inbound-smtp.${param.region}.amazonaws.com
    Route53RecordSetAdm:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: 16geniuses.com
        Name: 16geniuses.com
        Comment: Incoming email record for sub-domain
        Type: MX
        TTL: 900
        ResourceRecords:
          - 10 inbound-smtp.${param.region}.amazonaws.com

    SESReceiptRuleSet:
      Type: AWS::SES::ReceiptRuleSet
      Properties:
        RuleSetName: 'INBOUND'

    EmailRule1:
      Type: AWS::SES::ReceiptRule
      Properties:
        RuleSetName: !Ref SESReceiptRuleSet
        Rule:
          Name: '16geneticpersonalitytypes'
          Enabled: False
          Recipients:
            - 16geneticpersonalitytypes.com
          Actions:
            - S3Action:
                BucketName: ${param:bucket}
    EmailRule2:
      Type: AWS::SES::ReceiptRule
      Properties:
        RuleSetName: !Ref SESReceiptRuleSet
        Rule:
          Name: 16geniuses
          Enabled: True
          Recipients:
            - 16geniuses.com
          Actions:
            - S3Action:
                BucketName: ${param:bucket}
#            - LambdaAction:
#                FunctionArn:
#                  Fn::GetAtt:
#                    - ForwarderLambdaFunction
#                    - Arn
    S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${param:bucket}
        PolicyDocument:
          Statement:
            - Sid: "AllowSESPutObject"
              Effect: "Allow"
              Principal:
                Service: "ses.amazonaws.com"
              Action:
                - "s3:PutObject"
              Resource: arn:aws:s3:::${param:bucket}/*

    IAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: 16G-Serverless-Deployment-${param:region}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - 'cloudformation.amazonaws.com'
                  - 'lambda.amazonaws.com'
              Action:
                - 'sts:AssumeRole'
        Policies:
          - PolicyName: ServerlessDeploymentPolicies-${param:region}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow   # Allow S3 actions to buckets with service prefix.
                  Resource:
                    - arn:aws:s3:::${param:bucket}*'
                    - arn:aws:lambda:::*
                  Action:
                    - 's3:*'
                    - 'lambda:*'
          - PolicyName: LambdaRole-${param:region}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow   # Allow all IAM actions to roles prefixed with service
                  Resource:
                    - !Sub 'arn:aws:iam::${AWS::AccountId}:role/16G-Serverless-Deployment-Role'
                  Action:
                    - 'iam:PassRole'
                    -
    SESEmailIdentity16GPT:
      Type: AWS::SES::EmailIdentity
      Properties:
        EmailIdentity: 16geneticpersonalitytypes.com
        MailFromAttributes:
          MailFromDomain: mail.16geneticpersonalitytypes.com
        DkimAttributes:
          SigningEnabled: true

    SESEmailIdentity16Geniuses:
      Type: AWS::SES::EmailIdentity
      Properties:
        EmailIdentity: 16geniuses.com
        MailFromAttributes:
          MailFromDomain: mail.16geniuses.com
        DkimAttributes:
          SigningEnabled: true

    Route53RecordSetGroup16GPT:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId:
          Ref: SESEmailIdentity16GPT
        RecordSets:
          - Name: !GetAtt SESEmailIdentity16GPT.DkimDNSTokenName1
            Type: CNAME
            TTL: '3600'
            ResourceRecords:
              - !GetAtt SESEmailIdentity16GPT.DkimDNSTokenValue1
          - Name: !GetAtt SESEmailIdentity16GPT.DkimDNSTokenName2
            Type: CNAME
            TTL: '3600'
            ResourceRecords:
              - !GetAtt SESEmailIdentity16GPT.DkimDNSTokenValue2
          - Name: !GetAtt SESEmailIdentity16GPT.DkimDNSTokenName3
            Type: CNAME
            TTL: '3600'
            ResourceRecords:
              - !GetAtt SESEmailIdentity16GPT.DkimDNSTokenValue3

    Route53RecordSetGroup16Geniuses:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId:
          Ref: SESEmailIdentity16Geniuses
        RecordSets:
          - Name: !GetAtt SESEmailIdentity16Geniuses.DkimDNSTokenName1
            Type: CNAME
            TTL: '3600'
            ResourceRecords:
              - !GetAtt SESEmailIdSESEmailIdentity16Geniusesentity.DkimDNSTokenValue1
          - Name: !GetAtt SESEmailIdentity16Geniuses.DkimDNSTokenName2
            Type: CNAME
            TTL: '3600'
            ResourceRecords:
              - !GetAtt SESEmailIdentity16Geniuses.DkimDNSTokenValue2
          - Name: !GetAtt SESEmaiSESEmailIdentity16GeniuseslIdentity.DkimDNSTokenName3
            Type: CNAME
            TTL: '3600'
            ResourceRecords:
              - !GetAtt SESEmailIdentity16Geniuses.DkimDNSTokenValue3
